// Shared event data for Halifax-Now prototype
// Mix of real Halifax venues + invented events for the mockup

window.HFX_DATA = (function() {
  const CATEGORIES = [
    { id: 'music', label: 'Live Music' },
    { id: 'comedy', label: 'Comedy' },
    { id: 'arts', label: 'Arts & Culture' },
    { id: 'food', label: 'Food & Drink' },
    { id: 'community', label: 'Community' },
    { id: 'outdoors', label: 'Outdoors' },
    { id: 'film', label: 'Film' },
    { id: 'theatre', label: 'Theatre' },
    { id: 'sports', label: 'Sports' },
    { id: 'family', label: 'Family' },
    { id: 'nightlife', label: 'Nightlife' },
    { id: 'market', label: 'Markets' },
  ];

  const NEIGHBOURHOODS = [
    'North End', 'Downtown', 'South End', 'West End',
    'Dartmouth', 'Bedford', 'Quinpool', 'Spring Garden',
  ];

  const MOODS = [
    { id: 'chill', label: 'Chill', emoji: '🌙' },
    { id: 'rowdy', label: 'Rowdy', emoji: '🔥' },
    { id: 'date', label: 'Date Night', emoji: '💋' },
    { id: 'kids', label: 'Kid-friendly', emoji: '🧃' },
    { id: 'solo', label: 'Solo OK', emoji: '👤' },
    { id: 'crew', label: 'Bring a crew', emoji: '👯' },
    { id: 'free', label: 'Broke-friendly', emoji: '🪙' },
    { id: 'rainy', label: 'Rainy-day', emoji: '☔' },
  ];

  // Events — editorial blurbs written in NY Mag voice
  const EVENTS = [
    {
      id: 'e1',
      title: 'Halifax Jazz Festival — Opening Night',
      venue: 'The Carleton',
      address: '1685 Argyle St',
      hood: 'Downtown',
      category: 'music',
      date: '2026-04-24', // Fri
      time: '20:00',
      endTime: '23:30',
      price: 'free',
      priceLabel: 'Free',
      mood: ['chill', 'crew', 'date'],
      image: 'assets/evergreen.jpg',
      hue: 220,
      pick: true,
      blurb: 'The Carleton kicks off ten days of jazz with the HFX Quartet in the room, a fire in the hearth, and the kind of crowd that actually listens. Arrive by 7:30 if you want a seat.',
      short: 'The Carleton kicks off ten days of jazz with the HFX Quartet in the room.',
      critic: true,
    },
    {
      id: 'e2',
      title: 'Stand-Up Showcase',
      venue: "Yuk Yuk's",
      address: '1181 Hollis St',
      hood: 'Downtown',
      category: 'comedy',
      date: '2026-04-24',
      time: '21:00',
      price: 'paid',
      priceLabel: '$15',
      mood: ['rowdy', 'date', 'crew'],
      image: 'assets/vintage-christmas.webp',
      hue: 14,
      blurb: 'Six comics, one hour, one two-drink minimum. New faces on the early set — bring your poker face.',
      short: 'Six comics, one hour, two-drink minimum.',
    },
    {
      id: 'e3',
      title: 'AGNS First Fridays — Opening Reception',
      venue: 'Art Gallery of Nova Scotia',
      address: '1723 Hollis St',
      hood: 'Downtown',
      category: 'arts',
      date: '2026-04-24',
      time: '18:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['date', 'chill', 'solo'],
      image: 'assets/christkindl.png',
      hue: 280,
      pick: true,
      blurb: 'The gallery stays open late, there\'s free coffee, and nobody checks if you\'re talking about the art or just catching up. That\'s the point.',
      short: 'Gallery open late, free coffee, everybody talking.',
      critic: true,
    },
    {
      id: 'e4',
      title: 'Point Pleasant Sunday Run Club',
      venue: 'Point Pleasant Park',
      address: 'Tower Road entrance',
      hood: 'South End',
      category: 'outdoors',
      date: '2026-04-26',
      time: '09:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['solo', 'crew', 'chill'],
      image: 'assets/winter-market.webp',
      hue: 140,
      recurring: 'Every Sunday',
      blurb: '5K loop, all paces welcome, coffee at Glitter Bean after. Newcomers say hi at the Tower Road gate by 8:55.',
      short: '5K, all paces, coffee after.',
    },
    {
      id: 'e5',
      title: 'Propeller Tap Takeover',
      venue: 'Propeller Brewing Co.',
      address: '2015 Gottingen St',
      hood: 'North End',
      category: 'food',
      date: '2026-04-25',
      time: '14:00',
      price: 'free',
      priceLabel: 'Free entry',
      mood: ['rowdy', 'crew', 'chill'],
      image: null,
      hue: 40,
      blurb: 'Six breweries, one afternoon, a food truck in the parking lot. Bring your collapsible chair and your designated driver.',
      short: 'Six breweries, one afternoon, food truck outside.',
    },
    {
      id: 'e6',
      title: 'Carbon Arc: Cult Classics — Paris, Texas',
      venue: 'Carbon Arc Cinema',
      address: 'Museum of Natural History',
      hood: 'Downtown',
      category: 'film',
      date: '2026-04-23',
      time: '20:00',
      price: 'paid',
      priceLabel: '$12',
      mood: ['date', 'solo', 'chill'],
      image: null,
      hue: 20,
      blurb: 'Wim Wenders, 35mm, and the Harry Dean Stanton of it all. The best seats are the middle of row 4 and you didn\'t hear it from me.',
      short: 'Wenders, 35mm, Harry Dean Stanton.',
      critic: true,
    },
    {
      id: 'e7',
      title: 'Neptune Theatre — Spring Production Opening',
      venue: 'Neptune Theatre',
      address: '1593 Argyle St',
      hood: 'Downtown',
      category: 'theatre',
      date: '2026-04-27',
      time: '19:30',
      price: 'paid',
      priceLabel: '$25–$65',
      mood: ['date', 'crew'],
      image: null,
      hue: 340,
      blurb: 'A new piece from a local playwright, directed by someone who knows what she\'s doing. Tickets moving fast.',
      short: 'New local play, tickets moving fast.',
    },
    {
      id: 'e8',
      title: "Bearly's — Tuesday Blues Jam",
      venue: "Bearly's House of Blues",
      address: '1269 Barrington St',
      hood: 'Downtown',
      category: 'music',
      date: '2026-04-28',
      time: '21:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['rowdy', 'solo', 'crew'],
      image: null,
      hue: 210,
      recurring: 'Every Tuesday',
      blurb: 'The jam that\'s been running since before half the musicians in it were born. Bring your harmonica or your ears.',
      short: 'Running forever. Bring your harp or your ears.',
    },
    {
      id: 'e9',
      title: '2037 Gottingen — Open Mic & Community Potluck',
      venue: '2037 Gottingen St',
      address: '2037 Gottingen St',
      hood: 'North End',
      category: 'community',
      date: '2026-04-30',
      time: '18:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['chill', 'solo', 'crew'],
      image: null,
      hue: 120,
      blurb: 'Show up with a dish or don\'t. Read a poem or don\'t. Everyone welcome, which shouldn\'t feel rare but does.',
      short: 'Potluck + open mic. Everyone welcome.',
    },
    {
      id: 'e10',
      title: 'Dal Art Gallery — Artist Talk & Reception',
      venue: 'Dalhousie Art Gallery',
      address: '6101 University Ave',
      hood: 'South End',
      category: 'arts',
      date: '2026-04-29',
      time: '17:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['solo', 'date'],
      image: null,
      hue: 260,
      blurb: 'The artist is in the room. Ask her the thing you actually want to know.',
      short: 'Artist Q&A + reception.',
    },
    {
      id: 'e11',
      title: 'Good Robot — Trivia Night',
      venue: 'Good Robot Brewing',
      address: '2736 Robie St',
      hood: 'North End',
      category: 'food',
      date: '2026-04-29',
      time: '19:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['crew', 'rowdy'],
      image: null,
      hue: 170,
      recurring: 'Every Wednesday',
      blurb: 'Four rounds, one round of pizza, team of five max. The host is mean in a fun way.',
      short: 'Four rounds, team of five, host is mean.',
    },
    {
      id: 'e12',
      title: 'Alderney Landing — Farmer\'s Market',
      venue: 'Alderney Landing',
      address: '2 Ochterloney St, Dartmouth',
      hood: 'Dartmouth',
      category: 'market',
      date: '2026-04-25',
      time: '08:00',
      endTime: '13:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['chill', 'kids', 'solo'],
      image: null,
      hue: 60,
      recurring: 'Every Saturday',
      blurb: 'The ferry ride over is the first part of the morning. The oyster guy is the second part. The bread lady is the rest.',
      short: 'Ferry + oysters + bread. Classic Saturday.',
    },
    {
      id: 'e13',
      title: 'Halifax Mooseheads vs. Charlottetown Islanders',
      venue: 'Scotiabank Centre',
      address: '1800 Argyle St',
      hood: 'Downtown',
      category: 'sports',
      date: '2026-04-25',
      time: '19:00',
      price: 'paid',
      priceLabel: '$22+',
      mood: ['rowdy', 'crew', 'kids'],
      image: null,
      hue: 0,
      blurb: 'Final home stretch. Wear red, scream when appropriate.',
      short: 'Final home stretch. Wear red.',
    },
    {
      id: 'e14',
      title: 'The Seahorse — Hip Hop Night',
      venue: 'The Seahorse Tavern',
      address: '1665 Argyle St',
      hood: 'Downtown',
      category: 'nightlife',
      date: '2026-04-24',
      time: '22:00',
      price: 'paid',
      priceLabel: '$10',
      mood: ['rowdy', 'crew'],
      image: null,
      hue: 300,
      blurb: 'Local DJs, no dress code, sweat on the ceiling by midnight.',
      short: 'Local DJs. Sweat on the ceiling.',
    },
    {
      id: 'e15',
      title: 'Discovery Centre — Family Science Saturday',
      venue: 'Discovery Centre',
      address: '1215 Lower Water St',
      hood: 'Downtown',
      category: 'family',
      date: '2026-04-25',
      time: '10:00',
      price: 'paid',
      priceLabel: '$15 adult / $10 kid',
      mood: ['kids', 'rainy'],
      image: null,
      hue: 190,
      blurb: 'Hands-on experiments, a planetarium show at 11, and a gift shop you cannot get out of without buying something.',
      short: 'Experiments + planetarium at 11.',
    },
    {
      id: 'e16',
      title: 'The Company House — Songwriter Circle',
      venue: 'The Company House',
      address: '2202 Gottingen St',
      hood: 'North End',
      category: 'music',
      date: '2026-04-27',
      time: '20:00',
      price: 'paid',
      priceLabel: '$10',
      mood: ['chill', 'date', 'solo'],
      image: null,
      hue: 240,
      recurring: 'Every Monday',
      blurb: 'Four writers, one stage, no phones. The rule works.',
      short: 'Four writers, one stage, no phones.',
    },
    {
      id: 'e17',
      title: 'Seaport Market — Spring Makers Fair',
      venue: 'Halifax Seaport Farmers\' Market',
      address: '1209 Marginal Rd',
      hood: 'Downtown',
      category: 'market',
      date: '2026-04-26',
      time: '10:00',
      endTime: '15:00',
      price: 'free',
      priceLabel: 'Free',
      mood: ['kids', 'chill', 'date'],
      image: null,
      hue: 90,
      blurb: '60+ makers, a hot-chocolate stand run by a twelve-year-old that you should support.',
      short: '60+ makers. Support the kid with cocoa.',
    },
    {
      id: 'e18',
      title: 'Africville Museum — Heritage Walk',
      venue: 'Africville Museum',
      address: '5795 Africville Rd',
      hood: 'North End',
      category: 'community',
      date: '2026-04-26',
      time: '13:00',
      price: 'paid',
      priceLabel: 'By donation',
      mood: ['solo', 'chill'],
      image: null,
      hue: 30,
      pick: true,
      blurb: 'Led by community elders. Ninety minutes that will change how you see the harbour.',
      short: 'Ninety minutes with community elders.',
      critic: true,
    },
  ];

  return { CATEGORIES, NEIGHBOURHOODS, MOODS, EVENTS };
})();
